index:
  path: /
  controller: App\Controller\SiteController::sendNotification
  defaults:
    id: 0

notification-service:
  path: /users/send_notification/{id}
  controller: App\Controller\SiteController::sendNotification
  requirements:
    id: '\d+'
