# index:
#   path: /
#   controller: App\Controller\SiteController::index

notification-service:
  path: /users/send_notification/{id}
  controller: App\Controller\SiteController::sendNotification
  defaults:
    id: 1
  requirements:
    id: '\d+'
